package l2s.gameserver.network.l2.s2c;

import l2s.gameserver.geometry.Location;
import l2s.gameserver.model.Player;
import l2s.gameserver.model.base.Element;
import l2s.gameserver.model.base.Experience;
import l2s.gameserver.model.items.Inventory;
import l2s.gameserver.model.pledge.Alliance;
import l2s.gameserver.model.pledge.Clan;
import l2s.gameserver.network.l2.s2c.L2GameServerPacket;

public class GMViewCharacterInfoPacket
extends L2GameServerPacket {
    private Location _loc;
    private int[][] _inv;
    private int obj_id;
    private int _race;
    private int _sex;
    private int class_id;
    private int pvp_flag;
    private int karma;
    private int level;
    private int mount_type;
    private int _str;
    private int _con;
    private int _dex;
    private int _int;
    private int _wit;
    private int _men;
    private int curHp;
    private int maxHp;
    private int curMp;
    private int maxMp;
    private int curCp;
    private int maxCp;
    private int curLoad;
    private int maxLoad;
    private int rec_left;
    private int rec_have;
    private int _patk;
    private int _patkspd;
    private int _pdef;
    private int evasion;
    private int accuracy;
    private int crit;
    private int _matk;
    private int _matkspd;
    private int _mdef;
    private int _mEvasion;
    private int _mAccuracy;
    private int _mCrit;
    private int hair_style;
    private int hair_color;
    private int face;
    private int gm_commands;
    private int clan_id;
    private int clan_crest_id;
    private int ally_id;
    private int title_color;
    private int hero;
    private int private_store;
    private int name_color;
    private int pk_kills;
    private int pvp_kills;
    private int _runSpd;
    private int _walkSpd;
    private int _swimRunSpd;
    private int _swimWalkSpd;
    private int DwarvenCraftLevel;
    private int running;
    private int pledge_class;
    private String _name;
    private String title;
    private long _exp;
    private long _sp;
    private double move_speed;
    private double attack_speed;
    private double col_radius;
    private double col_height;
    private Element attackElement;
    private int attackElementValue;
    private int defenceFire;
    private int defenceWater;
    private int defenceWind;
    private int defenceEarth;
    private int defenceHoly;
    private int defenceUnholy;
    private int fame;
    private int talismans;
    private int _jewelsLimit;
    private double _expPercent;

    public GMViewCharacterInfoPacket(Player cha) {
        this._loc = cha.getLoc();
        this.obj_id = cha.getObjectId();
        this._name = cha.getName();
        this._race = cha.getRace().ordinal();
        this._sex = cha.getSex().ordinal();
        this.class_id = cha.getClassId().getId();
        this.level = cha.getLevel();
        this._exp = cha.getExp();
        this._str = cha.getSTR();
        this._dex = cha.getDEX();
        this._con = cha.getCON();
        this._int = cha.getINT();
        this._wit = cha.getWIT();
        this._men = cha.getMEN();
        this.curHp = (int)cha.getCurrentHp();
        this.maxHp = cha.getMaxHp();
        this.curMp = (int)cha.getCurrentMp();
        this.maxMp = cha.getMaxMp();
        this._sp = cha.getSp();
        this.curLoad = cha.getCurrentLoad();
        this.maxLoad = cha.getMaxLoad();
        this._patk = cha.getPAtk(null);
        this._patkspd = cha.getPAtkSpd();
        this._pdef = cha.getPDef(null);
        this.evasion = cha.getPEvasionRate(null);
        this.accuracy = cha.getPAccuracy();
        this.crit = cha.getPCriticalHit(null);
        this._matk = cha.getMAtk(null, null);
        this._matkspd = cha.getMAtkSpd();
        this._mdef = cha.getMDef(null, null);
        this._mEvasion = cha.getMEvasionRate(null);
        this._mAccuracy = cha.getMAccuracy();
        this._mCrit = cha.getMCriticalHit(null, null);
        this.pvp_flag = cha.getPvpFlag();
        this.karma = cha.getKarma();
        this._runSpd = cha.getRunSpeed();
        this._walkSpd = cha.getWalkSpeed();
        this._swimRunSpd = cha.getSwimRunSpeed();
        this._swimWalkSpd = cha.getSwimWalkSpeed();
        this.move_speed = cha.getMovementSpeedMultiplier();
        this.attack_speed = cha.getAttackSpeedMultiplier();
        this.mount_type = cha.getMountType().ordinal();
        this.col_radius = cha.getCurrentCollisionRadius();
        this.col_height = cha.getCurrentCollisionHeight();
        this.hair_style = cha.getBeautyHairStyle() > 0 ? cha.getBeautyHairStyle() : cha.getHairStyle();
        this.hair_color = cha.getBeautyHairColor() > 0 ? cha.getBeautyHairColor() : cha.getHairColor();
        this.face = cha.getBeautyFace() > 0 ? cha.getBeautyFace() : cha.getFace();
        this.gm_commands = cha.isGM() ? 1 : 0;
        this.title = cha.getTitle();
        this._expPercent = Experience.getExpPercent(cha.getLevel(), cha.getExp());
        Clan clan = cha.getClan();
        Alliance alliance = clan == null ? null : clan.getAlliance();
        this.clan_id = clan == null ? 0 : clan.getClanId();
        this.clan_crest_id = clan == null ? 0 : clan.getCrestId();
        this.ally_id = alliance == null ? 0 : alliance.getAllyId();
        this.private_store = cha.isInObserverMode() ? 7 : cha.getPrivateStoreType();
        this.DwarvenCraftLevel = Math.max(cha.getSkillLevel(1320), 0);
        this.pk_kills = cha.getPkKills();
        this.pvp_kills = cha.getPvpKills();
        this.rec_left = cha.getRecomLeft();
        this.rec_have = cha.getRecomHave();
        this.curCp = (int)cha.getCurrentCp();
        this.maxCp = cha.getMaxCp();
        this.running = cha.isRunning() ? 1 : 0;
        this.pledge_class = cha.getPledgeRank().ordinal();
        this.hero = cha.isHero() ? 1 : 0;
        this.name_color = cha.getNameColor();
        this.title_color = cha.getTitleColor();
        this.attackElement = cha.getAttackElement();
        this.attackElementValue = cha.getAttack(this.attackElement);
        this.defenceFire = cha.getDefence(Element.FIRE);
        this.defenceWater = cha.getDefence(Element.WATER);
        this.defenceWind = cha.getDefence(Element.WIND);
        this.defenceEarth = cha.getDefence(Element.EARTH);
        this.defenceHoly = cha.getDefence(Element.HOLY);
        this.defenceUnholy = cha.getDefence(Element.UNHOLY);
        this.fame = cha.getFame();
        this.talismans = cha.getTalismanCount();
        this._jewelsLimit = cha.getJewelsLimit();
        this._inv = new int[38][4];
        for (int PAPERDOLL_ID : Inventory.PAPERDOLL_ORDER) {
            this._inv[PAPERDOLL_ID][0] = cha.getInventory().getPaperdollObjectId(PAPERDOLL_ID);
            this._inv[PAPERDOLL_ID][1] = cha.getInventory().getPaperdollItemId(PAPERDOLL_ID);
            this._inv[PAPERDOLL_ID][2] = cha.getInventory().getPaperdollVariation1Id(PAPERDOLL_ID);
            this._inv[PAPERDOLL_ID][3] = cha.getInventory().getPaperdollVariation2Id(PAPERDOLL_ID);
        }
    }

    @Override
    protected final void writeImpl() {
        this.writeD(this._loc.x);
        this.writeD(this._loc.y);
        this.writeD(this._loc.z);
        this.writeD(this._loc.h);
        this.writeD(this.obj_id);
        this.writeS(this._name);
        this.writeD(this._race);
        this.writeD(this._sex);
        this.writeD(this.class_id);
        this.writeD(this.level);
        this.writeQ(this._exp);
        this.writeF(this._expPercent);
        this.writeD(this._str);
        this.writeD(this._dex);
        this.writeD(this._con);
        this.writeD(this._int);
        this.writeD(this._wit);
        this.writeD(this._men);
        this.writeD(0);
        this.writeD(0);
        this.writeD(this.maxHp);
        this.writeD(this.curHp);
        this.writeD(this.maxMp);
        this.writeD(this.curMp);
        this.writeQ(this._sp);
        this.writeD(this.curLoad);
        this.writeD(this.maxLoad);
        this.writeD(this.pk_kills);
        for (int PAPERDOLL_ID : Inventory.PAPERDOLL_ORDER) {
            this.writeD(this._inv[PAPERDOLL_ID][0]);
        }
        for (int PAPERDOLL_ID : Inventory.PAPERDOLL_ORDER) {
            this.writeD(this._inv[PAPERDOLL_ID][1]);
        }
        for (int PAPERDOLL_ID : Inventory.PAPERDOLL_ORDER) {
            if (PAPERDOLL_ID == 19) break;
            this.writeD(this._inv[PAPERDOLL_ID][2]);
            this.writeD(this._inv[PAPERDOLL_ID][3]);
        }
        this.writeC(this.talismans);
        this.writeC(this._jewelsLimit);
        this.writeD(0);
        this.writeH(0);
        this.writeD(this._patk);
        this.writeD(this._patkspd);
        this.writeD(this._pdef);
        this.writeD(this.evasion);
        this.writeD(this.accuracy);
        this.writeD(this.crit);
        this.writeD(this._matk);
        this.writeD(this._matkspd);
        this.writeD(this._patkspd);
        this.writeD(this._mdef);
        this.writeD(this._mEvasion);
        this.writeD(this._mAccuracy);
        this.writeD(this._mCrit);
        this.writeD(this.pvp_flag);
        this.writeD(this.karma);
        this.writeD(this._runSpd);
        this.writeD(this._walkSpd);
        this.writeD(this._swimRunSpd);
        this.writeD(this._swimWalkSpd);
        this.writeD(this._runSpd);
        this.writeD(this._walkSpd);
        this.writeD(this._runSpd);
        this.writeD(this._walkSpd);
        this.writeF(this.move_speed);
        this.writeF(this.attack_speed);
        this.writeF(this.col_radius);
        this.writeF(this.col_height);
        this.writeD(this.hair_style);
        this.writeD(this.hair_color);
        this.writeD(this.face);
        this.writeD(this.gm_commands);
        this.writeS(this.title);
        this.writeD(this.clan_id);
        this.writeD(this.clan_crest_id);
        this.writeD(this.ally_id);
        this.writeC(this.mount_type);
        this.writeC(this.private_store);
        this.writeC(this.DwarvenCraftLevel);
        this.writeD(this.pk_kills);
        this.writeD(this.pvp_kills);
        this.writeH(this.rec_left);
        this.writeH(this.rec_have);
        this.writeD(this.class_id);
        this.writeD(0);
        this.writeD(this.maxCp);
        this.writeD(this.curCp);
        this.writeC(this.running);
        this.writeC(321);
        this.writeD(this.pledge_class);
        this.writeC(0);
        this.writeC(this.hero);
        this.writeD(this.name_color);
        this.writeD(this.title_color);
        this.writeH(this.attackElement.getId());
        this.writeH(this.attackElementValue);
        this.writeH(this.defenceFire);
        this.writeH(this.defenceWater);
        this.writeH(this.defenceWind);
        this.writeH(this.defenceEarth);
        this.writeH(this.defenceHoly);
        this.writeH(this.defenceUnholy);
        this.writeD(this.fame);
        this.writeD(0);
        this.writeD(0);
        this.writeD(0);
    }
}

